model:
  image_channels: 3

  lam_model_dim: 1024
  lam_latent_dim: 32
  lam_patch_size: 16
  lam_enc_blocks: 16
  lam_dec_blocks: 16
  lam_num_heads: 16
  lam_causal_temporal: true

  beta: 0.0002
  log_interval: 500
  log_path: /scratch/a/ankur99/WORLD_MODEL_PROJECT/lam/lam_logs/exp_imgs_ssv2_our_mira_seg_bs12_lr5e6
  optimizer:
    class_path: torch.optim.AdamW
    init_args:
      lr: 5e-6
      weight_decay: 1e-2

# ---- CC: segment-level (T=8), bs12, lr=5e-6 ----
data:
  batch_size: 12
  data_root: /scratch/a/ankur99/WORLD_MODEL_PROJECT/parquet_data
  env_source: ssv2_our_mira
  padding: repeat
  randomize: true
  resolution: 256
  num_frames: 8
  output_format: t h w c
  samples_per_epoch: 1000000
  sampling_strategy: dataset

trainer:
  max_epochs: 1000
  accelerator: gpu
  num_nodes: 1
  devices: 0,1,2,3
  strategy: ddp_find_unused_parameters_false
  precision: 16-mixed
  log_every_n_steps: 500
  accumulate_grad_batches: 4
  gradient_clip_val: 0.3

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: /scratch/a/ankur99/WORLD_MODEL_PROJECT/lam/lam_logs/exp_ckpts_ssv2_our_mira_seg_bs12_lr5e6
        verbose: true
        save_last: true
        save_top_k: -1
        every_n_train_steps: 9000

  logger:
    - class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        save_dir: /scratch/a/ankur99/WORLD_MODEL_PROJECT/lam/lam_logs
        name: lam_ssv2_our_mira_seg_bs12_lr5e6
    - class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        project: adaworld-lam
        name: lam_ssv2_our_mira_cc_seg_bs12_lr5e6
        id: lam-ssv2-our-mira-cc-seg-bs12-lr5e6
        resume: allow
        save_dir: /scratch/a/ankur99/WORLD_MODEL_PROJECT/lam/lam_logs
